del /S ..\*.hpp
del /S ..\*.obj
del /S ..\*.tds
del /S ..\*.map
del /S ..\*.#00
del /S ..\*.csm
del /S ..\*.bpi
del /S ..\*.lib
del /S ..\*.ilc
del /S ..\*.ild
del /S ..\*.ilf
del /S ..\*.ils
del /S ..\*.cgi
del /S ..\*.drc
del /S ..\*.$*
del /S ..\*.dcu
del /S ..\*.bak
del /S ..\*.~*
del /S ..\*.dpu
del /S ..\*.cfg
del /S ..\*.ddp
del /S ..\*_orig_?.*
del /S ..\*.ressrc
del /S ..\.#*
del /S ..\*.local
del /S ..\__history
del /S ..\*.gex
del /S ..\*.identcache
del /S ..\*.dsk
